delete from stop;
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (1,'','Grand Central Terminal',null,40.752998);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (4,'','Harlem-125th St.',null,40.805157);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (622,'','Yankees-E153 St.',null,40.8253);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (9,'','Morris Heights',null,40.854252);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (10,'','University Heights',null,40.862248);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (11,'','Marble Hill',null,40.874333);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (14,'','Spuyten Duyvil',null,40.878245);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (16,'','Riverdale',null,40.903981);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (17,'','Ludlow',null,40.924972);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (18,'','Yonkers',null,40.935795);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (19,'','Glenwood',null,40.950496);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (20,'','Greystone',null,40.97104);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (22,'','Hastings-on-Hudson',null,40.994109);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (23,'','Dobbs Ferry',null,41.012459);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (24,'','Ardsley-on-Hudson',null,41.026198);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (25,'','Irvington',null,41.039993);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (27,'','Tarrytown',null,41.076473);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (29,'','Philipse Manor',null,41.09492);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (30,'','Scarborough',null,41.135763);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (31,'','Ossining',null,41.157663);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (33,'','Croton Harmon',null,41.192391);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (37,'','Cortlandt',null,41.246259);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (39,'','Peekskill',null,41.285962);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (40,'','Manitou',null,41.335181);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (42,'','Garrison',null,41.38178);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (43,'','Cold Spring',null,41.415283);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (44,'','Breakneck Ridge',null,41.450181);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (46,'','Beacon',null,41.504007);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (49,'','New Hamburg',null,41.587448);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (51,'','Poughkeepsie',null,41.705839);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (54,'','Melrose',null,40.825761);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (55,'','Tremont',null,40.847301);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (56,'','Fordham',null,40.8615);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (57,'','Botanical Garden',null,40.866555);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (58,'','Williams Bridge',null,40.878569);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (59,'','Woodlawn',null,40.895361);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (61,'','Wakefield',null,40.905424);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (62,'','Mt Vernon West',null,40.912142);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (64,'','Fleetwood',null,40.92699);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (65,'','Bronxville',null,40.93978);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (66,'','Tuckahoe',null,40.949393);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (68,'','Crestwood',null,40.958997);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (71,'','Scarsdale',null,40.989168);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (72,'','Hartsdale',null,41.010333);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (74,'','White Plains',null,41.032589);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (76,'','North White Plains',null,41.049806);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (78,'','Valhalla',null,41.072819);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (79,'','Mount Pleasant',null,41.097165);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (80,'','Hawthorne',null,41.097218);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (81,'','Pleasantville',null,41.135222);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (83,'','Chappaqua',null,41.158015);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (84,'','Mount Kisco',null,41.208242);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (85,'','Bedford Hills',null,41.237316);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (86,'','Katonah',null,41.259552);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (88,'','Golden''s Bridge',null,41.294338);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (89,'','Purdy''s',null,41.325775);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (90,'','Croton Falls',null,41.347722);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (91,'','Brewster',null,41.39447);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (94,'','Southeast',null,41.413203);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (97,'','Patterson',null,41.511827);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (98,'','Pawling',null,41.564205);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (99,'','Appalachian Trail',null,41.61081);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (100,'','HM Valley-Wingdale',null,41.637525);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (101,'','Dover Plains',null,41.740401);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (176,'','Tenmile River',null,41.779938);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (177,'','Wassaic',null,41.821579);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (105,'','Mt Vernon East',null,40.912161);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (106,'','Pelham',null,40.910321);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (108,'','New Rochelle',null,40.911605);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (110,'','Larchmont',null,40.933394);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (111,'','Mamaroneck',null,40.954061);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (112,'','Harrison',null,40.969432);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (114,'','Rye',null,40.986744);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (115,'','Port Chester',null,41.000732);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (116,'','Greenwich',null,41.021277);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (118,'','Cos Cob',null,41.030171);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (120,'','Riverside',null,41.031682);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (121,'','Old Greenwich',null,41.033817);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (124,'','Stamford',null,41.046611);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (153,'','Glenbrook',null,41.070547);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (154,'','Springdale',null,41.08876);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (155,'','Talmadge Hill',null,41.116012);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (157,'','New Canaan',null,41.146305);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (127,'','Noroton Heights',null,41.069041);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (128,'','Darien',null,41.076913);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (129,'','Rowayton',null,41.077456);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (131,'','South Norwalk',null,41.09673);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (158,'','Merritt 7',null,41.143382);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (160,'','Wilton',null,41.196202);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (161,'','Cannondale',null,41.21662);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (162,'','Branchville',null,41.26763);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (163,'','Redding',null,41.325684);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (164,'','Bethel',null,41.378159);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (165,'','Danbury',null,41.396363);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (133,'','East Norwalk',null,41.103996);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (134,'','Westport',null,41.118928);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (136,'','Green''s Farms',null,41.122265);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (137,'','Southport',null,41.134844);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (138,'','Fairfield',null,41.143077);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (140,'','Bridgeport',null,41.178677);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (143,'','Stratford',null,41.194255);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (167,'','Derby',null,41.319718);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (168,'','Ansonia',null,41.340272);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (169,'','Seymour',null,41.395139);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (170,'','Beacon Falls',null,41.441752);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (171,'','Naugatuck',null,41.494204);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (172,'','Waterbury',null,41.552728);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (145,'','Milford',null,41.223231);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (149,'','New Haven',null,41.296501);
insert into stop (stop_id, stop_name, stop_desc, stop_lat, stop_lon) values (151,'','NH-State St.',null,41.304979);
